vim.opt.autoindent = false
vim.opt.backup = true
vim.opt.backupdir = "${XDG_STATE_HOME:-${HOME}/.local/state}/nvim/backup/,/tmp/"
vim.opt.backupskip = "/tmp/*"
vim.opt.clipboard = "unnamedplus"
vim.opt.confirm = true
vim.opt.cursorcolumn = true
vim.opt.cursorline = true
vim.opt.dictionary = "/usr/share/dict/words"
vim.opt.diff = true
--vim.opt.expandtab = true
vim.opt.expandtab = false
vim.opt.ignorecase = true
vim.opt.jumpoptions = "stack"
vim.opt.list = true
vim.opt.listchars = "eol: ,tab:  ,space: ,multispace: ,lead: ,leadmultispace: ,trail:○,extends:>,precedes:<,conceal: ,nbsp:%"
vim.opt.matchpairs = "(:),{:},[:],<:>"
vim.opt.mouse = "iv"
vim.opt.number = true
--vim.opt.shiftwidth = 4
vim.opt.shiftwidth = 0
vim.opt.shiftround = true
vim.opt.smartindent = true
vim.opt.smarttab = false
vim.opt.softtabstop = 4
vim.opt.statuscolumn = "%=%{v:relnum?v:relnum:v:lnum} "
vim.opt.statusline = "%<%f %h%m%r%=%-14.(%l,%c%V%) %P 「できるよ！」"
vim.opt.tabstop = 4
vim.opt.undofile = true
vim.opt.wrap = true -- false
