#!/bin/bash

szh xdg -ae # Make sure XDG variables are setup

# Flag management
q_flag='v'
s_flag='false'
while getopts 'hsq' flag; do
    case "${flag}" in
        s) s_flag='true' ;;
        q) q_flag='' ;;
        *) szh usage '[-h(help)s(udo)q(uiet)]' || exit 1 ;;
    esac
done

szh prompt -ns 'This will make changes in XDG and $HOME directories, are you sure?' || exit 1 # Request permission

# Copy over application config
mkdir "-p${q_flag}" "${XDG_CONFIG_HOME}"
for app in "$(szh find -t 'd')"; do
    ln "-fs${q_flag}" "${PWD}/.config/${app}" "${XDG_CONFIG_HOME}"
done
unset app

# Additional setup for applications that doesn't follow XDG Base Directory specification
ln "-fs${q_flag}" "${XDG_CONFIG_HOME}/bash/.inputrc" "${HOME}/.inputrc"

CWD="${BASH_SOURCE[0]}"

if [[ "${s_flag}" = true ]]; then
    sudo ln "-fs${q_flag}" "${PWD}/.config/bash/.inputrc" '/root/.inputrc'
    sudo ln "-fs${q_flag}" "${PWD}/.config/bash/bash.bashrc" '/etc/bash.bashrc'
    sudo ln "-fs${q_flag}" "${PWD}/.config/bash/profile" '/etc/profile'
    sudo ln "-fs${q_flag}" '/usr/bin/python3' '/usr/bin/python'
fi

unset q_flag
unset s_flag
