#!/bin/bash -i

dirname $0 || exit 1 # Check if running bash

source "$PWD/.config/bash/bashrc/0_helper.sh" # Source initially to use functions
source "$PWD/.config/bash/profile/0_xdg_specification.sh" # Source initially to use XDG vars

# Flag management
q_flag='v'
s_flag=false
while getopts 'qs' flag; do
    case "$flag" in
        q) q_flag='' ;;
        s) s_flag=true ;;
        *) echo "Usage: setup [qs]" ;;
    esac
done

prompt 'This will make changes in XDG and $HOME directories, are you sure?' false # Request permission

# Copy over application config
mkdir -p$q_flag "$XDG_CONFIG_HOME"
for app in $(find $PWD/.config -mindepth 1 -maxdepth 1 -type d -printf '%f\n'); do
    if [[ ! -L "$XDG_CONFIG_HOME/$app" ]] || [[ ! -e "$XDG_CONFIG_HOME" ]]; then
        ln -fs$q_flag "$PWD/.config/$app" "$XDG_CONFIG_HOME/$app"
    fi
done

# Additional setup for applications that doesn't follow XDG Base Directory specification
ln -fs$q_flag "$XDG_CONFIG_HOME/bash/.bashrc" "$HOME/.bashrc"
ln -fs$q_flag "$XDG_CONFIG_HOME/bash/.profile" "$HOME/.profile"
ln -fs$q_flag "$XDG_CONFIG_HOME/git/.gitconfig" "$HOME/.gitconfig"

unset app
unset q_flag
unset s_flag
