# Binds
bind = super,d,	exec, wofi --show drun --allow-images
bind = super,e,	exec, thunar
bind = super,t,	exec, kitty
bind = ,print,	exec, grim -g "$(slurp)" - | tee >(wl-copy) | swappy -f -
bind = ,alt_r,	exec, rofimoji --selector wofi --action copy && sleep 0.05 && wtype "$(wl-paste)"

# Startup
exec-once =		mpvpaper '*' ${HOME}/AppData/hypr/wallpaper.mp4 --mpv-options="--loop-file=inf"
exec-once =		thunderbird
exec-once =		todoist
exec-once =		ktailctl
exec-once =		streamdeck -n

exec-once =		waybar -c ~/.config/waybar/DP-1.config -s ~/.config/waybar/style.css
exec-once =		waybar -c ~/.config/waybar/DP-2.config -s ~/.config/waybar/style.css
exec-once =		waybar -c ~/.config/waybar/DP-3.config -s ~/.config/waybar/style.css
exec-once =		waybar -c ~/.config/waybar/HDMI-A-1.config -s ~/.config/waybar/style.css

exec-once =		fcitx5 -d
