# Configurations
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/hyprland.conf
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/windows.conf
source = ~/.config/hypr/config/workspaces.conf
source = ~/.config/hypr/config/visuals.conf
source = ~/.config/hypr/config/inputs.conf
