# VIM supremacy
input {
    kb_layout = us
    kb_options = caps:swapescape
}

# Audio signals
bind = , XF86AudioPlay,	exec, ~/AppData/streamdeckui/scripts/media-pause-toggle.sh
bind = , XF86AudioPrev,	exec, ~/AppData/streamdeckui/scripts/media-previous.sh
bind = , XF86AudioNext,	exec, ~/AppData/streamdeckui/scripts/media-next.sh
bind = , XF86AudioMute,	exec, ~/AppData/streamdeckui/scripts/audio-sink-mute-toggle.sh
