# Session
bind = super+shift,f1,	exec, hyprctl keyword decoration:inactive_opacity 0.4
bind = super+shift,f2,	exec, hyprctl keyword decoration:inactive_opacity 0.8
bind = super+shift,f4,	exit
bind = super+shift,f5,	exec, hyprland reload
