windowrule = match:class com.saivert.pwvucontrol, float on
windowrule = match:class com.saivert.pwvucontrol, size 1600 900
windowrule = match:class com.saivert.pwvucontrol, center on
windowrule = match:class com.saivert.pwvucontrol, workspace special:volumemixer silent

bind = super,v,	togglespecialworkspace, volumemixer
