# General
bind = super,w,				killactive
bind = super,space,			togglefloating
bind = super,c,				centerwindow
bind = super,p,				pin

# Focus
bind = super,$left,			movefocus, l
bind = super,$down,			movefocus, d
bind = super,$up,			movefocus, u
bind = super,$right,		movefocus, r

# Moving
bind = super+shift,$left,	movewindow, l
bind = super+shift,$down,	movewindow, d
bind = super+shift,$up,		movewindow, u
bind = super+shift,$right,	movewindow, r


# Resizing
bind = super+alt,$left,		resizeactive, -20 0
bind = super+alt,$down,		resizeactive, 0 -20
bind = super+alt,$up,		resizeactive, 0 20
bind = super+alt,$right,	resizeactive, 20 0

# Mouse controls
bindm = super, mouse:$left_click,	movewindow # move windows
bindm = super, mouse:$right_click,	resizewindow # resize windows
