for profile_file in "${XDG_CONFIG_HOME}/bash/profile_files"/* ; do
    source "${profile_file}"
done

[[ -f "${XDG_CONFIG_HOME}/bash/bashrc" ]] && source "${XDG_CONFIG_HOME}/bash/bashrc" # invoke bashrc

unset profile_file
