[manager]
theme = "catppuccin-mocha"

show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "size"

[preview]
max_width  = 1000
max_height = 1000

image = true
video = true
pdf = true

[ui]
border = "rounded"

[filetype]
rules = [
  { mime = "image/*", fg = "#E5C890" },
  { mime = "video/*", fg = "#8CAAEE" },
  { mime = "audio/*", fg = "#A6D189" },
  { mime = "application/pdf", fg = "#F4B8E4" },
]
