STARSHIP_CONFIG='/home/sizzleru/.config/starship/starship.toml'
STARSHIP_CACHE='/home/sizzleru/.cache/starship/cache'
PYTHON_HISTORY='/home/sizzleru/.local/state/python/history'
CUDA_CACHE_PATH='/home/sizzleru/.cache/nv'
PYTHON_HISTORY='/home/sizzleru/.local/state/python/history'
alias nvidia-settings='nvidia-settings --config=/home/sizzleru/.config/nvidia/settings'
HISTFILE='/home/sizzleru/.local/state/bash/history'
XINITRC='/home/sizzleru/.config/X11/xinitrc'
INPUTRC='/home/sizzleru/.config/readline/inputrc'
