# Binds
bind = super,d,	exec,	wofi --show drun
bind = super,t,	exec, kitty

# Startup
exec-once =		waybar
exec-once =		mpvpaper '*' ${HOME}/Assets/Videos/Wallpapers/2560x1440/eyes.mp4 --mpv-options="--loop-file=inf"
