# Binds
bind = super,d,	exec, wofi --show drun
bind = super,e,	exec, thunar
bind = super,t,	exec, kitty
bind = ,print,	exec, grim -g "$( slurp )" - | swappy -f -

# Startup
exec-once =		waybar
exec-once =		mpvpaper '*' ${HOME}/Assets/Videos/Wallpapers/2560x1440/eyes.mp4 --mpv-options="--loop-file=inf"
exec-once =		thunderbird
exec-once =		todoist
