general {

	# gaps
	gaps_in = 6
	gaps_out = 12

	# borders
	border_size = 2
	col.active_border = 	rgba(f5c2e7ff)
	col.inactive_border =	rgba(1e1e2eff)
}

decoration {
	rounding = 12

	#drop_shadow = true
	#shadow_range = 6
	#shadow_render_power = 2
	#col.shadow = rgba(00000055)

	blur {
		enabled = true
		size = 6
		passes = 2
		new_optimizations = true
	}

	inactive_opacity = 0.8
	active_opacity = 1
}

animations {
	enabled = true
	
	bezier = easeOut, 0.16, 1, 0.3, 1
	
	animation = windows, 1, 6, easeOut
	animation = border, 1, 10, default
	animation = fade, 1, 6, easeOut
	animation = workspaces, 1, 5, easeOut
}

env = XCURSOR_THEME,catppuccin-mocha-pink-cursors
env = XCURSOR_SIZE,24
