#case $(hostnamectl --static) in
#    academy) HOSTNAME_LOGO=🏫 ;;
#    city) HOSTNAME_LOGO=🏙️ ;;
#    daisy) HOSTNAME_LOGO=🌼 ;;
#    forest) HOSTNAME_LOGO=🌲 ;;
#    moon) HOSTNAME_LOGO=🌕 ;;
#    power) HOSTNAME_LOGO=⚡ ;;
#    space) HOSTNAME_LOGO=🌌 ;;
#    stone) HOSTNAME_LOGO=🪨 ;;
#    tree) HOSTNAME_LOGO=🌳 ;;
#    workshop) HOSTNAME_LOGO=🛠️ ;;
#    *) HOSTNAME_LOGO=❓ ;;
#esac

#format = '''
#[ ┌───────────────────> ](bold green)
#[ │](bold green) $all
#[ └─>](bold green) '''
#format = '''
#[ ╔═══════════════════> ](bold green)
#[ ║](bold green) $all
#[ ╚═>](bold green) '''

format = """
[ ╭───────────────────▸ ](bold green)
[ │ ](bold green)$sudo$username$os${custom.hostname}$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch$fossil_metrics$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$nats$direnv$env_var$crystal$custom$cmd_duration$line_break$jobs$battery$time$status$container$shell$character
[ ╰─▸](bold green) """

[line_break]
disabled = true

[character]
disabled = true

[sudo]
disabled = false
symbol = '☣'
format = '[$symbol ]($style)'

[username]
show_always = true
format = '[$user]($style) '

[hostname]
disabled = true
ssh_only = false
ssh_symbol = '◉ '
format = '[\($ssh_symbol$hostname\)]($style) '

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'

[git_metrics]
disabled = false

[os]
disabled = true
format = '[$symbol]($style)'

[status]
disabled = false

[jobs]
number_threshold = 1
symbol = '⚙'

[custom.hostname]
command = "hostnamectl hostname | xargs ${XDG_CONFIG_HOME}/starship/hostname.sh"
when = true
shell = 'bash'
format = '[❨$output❩]($style) '
