#format = '''
#[ ┌───────────────────> ](bold green)
#[ │](bold green) $all
#[ └─>](bold green) '''

#format = '''
#[ ╔═══════════════════> ](bold green)
#[ ║](bold green) $all
#[ ╚═>](bold green) '''

format = '''
[ ╭───────────────────▸ ](bold green)
[ │](bold green) $all
[ ╰─▸](bold green) '''

[line_break]
disabled = true

[character]
disabled = true

[username]
show_always = true
format = '[$user]($style) '

[hostname]
ssh_only = false
ssh_symbol = '◉'
format = '[\($ssh_symbol$hostname\)]($style) '

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'

[fill]
symbol = '-'
style = 'bold green'

#case $(hostnamectl --static) in
#    academy) HOSTNAME_LOGO=🏫 ;;
#    city) HOSTNAME_LOGO=🏙️ ;;
#    daisy) HOSTNAME_LOGO=🌼 ;;
#    forest) HOSTNAME_LOGO=🌲 ;;
#    moon) HOSTNAME_LOGO=🌕 ;;
#    power) HOSTNAME_LOGO=⚡ ;;
#    space) HOSTNAME_LOGO=🌌 ;;
#    stone) HOSTNAME_LOGO=🪨 ;;
#    tree) HOSTNAME_LOGO=🌳 ;;
#    workshop) HOSTNAME_LOGO=🛠️ ;;
#    *) HOSTNAME_LOGO=❓ ;;
#esac
