# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
#add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
#
#format = '$all'

[username]
show_always = true
format = '[$user]($style) '

[hostname]
ssh_only = false
format = '[\($ssh_symbol$hostname\) ]($style)'

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'

#case $(hostnamectl --static) in
#    academy) HOSTNAME_LOGO=🏫 ;;
#    city) HOSTNAME_LOGO=🏙️ ;;
#    daisy) HOSTNAME_LOGO=🌼 ;;
#    forest) HOSTNAME_LOGO=🌲 ;;
#    moon) HOSTNAME_LOGO=🌕 ;;
#    power) HOSTNAME_LOGO=⚡ ;;
#    space) HOSTNAME_LOGO=🌌 ;;
#    stone) HOSTNAME_LOGO=🪨 ;;
#    tree) HOSTNAME_LOGO=🌳 ;;
#    workshop) HOSTNAME_LOGO=🛠️ ;;
#    *) HOSTNAME_LOGO=❓ ;;
#esac
